apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: first-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 5M
spec:
 rules:
   - host: http://aad10418a4fcf4b039b9581fe4752418-06b14723f3efad7e.elb.ap-south-1.amazonaws.com/
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: ingress-service
               port:
                 number: 80