name: Connect to Servers

on:
  push:
    paths:
      - '.github/workflows/connectToPvtEC2.yml'  # Only trigger when deploy.yml is modified

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables
        run: |
          echo "Loading variables..."
          echo "TARGET_HOST=$(cat vars.env | grep TARGET_HOST | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Connect to Bastion Host
        env:
          BASTION_PRIVATE_KEY: ${{ secrets.BASTION_PVT_KEY }}
          TARGET_SERVER_PVT_KEY: ${{ secrets.TARGET_SERVER_PVT_KEY }}
        run: |
          echo "Connecting to Bastion Host..."
          mkdir -p ~/.ssh
          echo "$BASTION_PRIVATE_KEY" > ~/.ssh/bastion_key.pem
          chmod 600 ~/.ssh/bastion_key.pem
          ssh -i ~/.ssh/bastion_key.pem -o StrictHostKeyChecking=no ec2-user@13.235.31.183 << EOF
            echo "Creating test file on Bastion..."
            echo "Hello, From Bastion i.e public ec2 machine" > /home/ec2-user/bastion_test_file.txt 
            echo "Connecting to Target Host..."
            ssh -i /home/ec2-user/vpc-endpoint.pem -o StrictHostKeyChecking=no ec2-user@$TARGET_HOST << TARGET_EOF
              echo "Creating test file on Target Host..."
              echo "Hello, From target machine i.e private ec2 machine with pvt ip :$TARGET_HOST" > /home/ec2-user/target_test_file.txt
            TARGET_EOF
          EOF
